tarsnap: remove file logging + sending of mail after backup
We can use cron functionality to get the output of the script
after execution. There is no need to reimplement mail functionality in
the script.

diff --git a/tarsnap/tarsnap b/tarsnap/tarsnap
--- a/tarsnap/tarsnap
+++ b/tarsnap/tarsnap
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-logfile="/tmp/tarsnap.log"
-mailto="fho"
-
 excludes="--exclude /dev/ --exclude /sys/ --exclude /proc/ \
 	  --exclude /tmp/ --exclude /var/tmp/ --exclude /mnt/attachments \
 	  --exclude /mnt/usbstick --exclude /mnt/whiteshark --exclude /media/ \
@@ -26,19 +23,18 @@ backup()
 	echo "Starting $archive_name ($dirs) backup"
 	sleep 1
 	tarsnap -c -f $archive_name-$(date +%Y%m%d) $opts \
-		$excludes $dirs 2>&1 | tee -a "$logfile"
+		$excludes $dirs
 	return $?
 }
 
 
 wall "Tarsnap backup started"
-rm "$logfile"
 failed=0
 subject="$hostname Backup"
 backup home /home /root || failed=1
 backup etc /etc || failed=1
-backup data /data || failed=1
-backup crypt /mnt/crypt ||failed=1
+#backup data /data || failed=1
+backup crypt /mnt/crypt || failed=1
 if [ $failed -eq 1 ]; then
 	subject="$subject Failed"
 else
@@ -46,4 +42,3 @@ else
 fi
 
 wall "Tarsnap backup finished"
-cat "$logfile" | mail -s "$subject" $mailto
